import io
from datetime import datetime

import pandas as pd
import streamlit as st
from jinja2 import Template
from weasyprint import HTML

# ==========================================
# 1. ATO 报表 HTML 模板 (Jinja2)
# ==========================================
ATO_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px;
                  border-bottom: 2px solid #000; padding-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; }
        .subtitle { font-size: 14px; color: #555; }
        .section { margin-bottom: 15px; }
        .section-title { font-weight: bold; background-color: #eee;
                         padding: 5px; margin-bottom: 5px; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
        .info-item { margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ccc; padding: 5px; text-align: left; }
        th { background-color: #f9f9f9; }
        .total-row { font-weight: bold; background-color: #eee; }
        .signature-box { margin-top: 30px; border: 1px solid #000; padding: 20px; height: 50px; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #888; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Australian Taxation Office</div>
        <div class="subtitle">Cross-Border Goods Trade Declaration (Form N10)</div>
    </div>

    <div class="section">
        <div class="section-title">Section A: Taxpayer Information</div>
        <div class="info-grid">
            <div class="info-item"><strong>ABN:</strong> {{ abn }}</div>
            <div class="info-item"><strong>Company Name:</strong> {{ company_name }}</div>
            <div class="info-item"><strong>Contact Person:</strong> {{ contact }}</div>
            <div class="info-item"><strong>Report Date:</strong> {{ report_date }}</div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Section B: Transaction Details</div>
        <table>
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Dutiable Value (AUD)</th>
                    <th>Tax Rate (%)</th>
                    <th>Duty Amount (AUD)</th>
                </tr>
            </thead>
            <tbody>
                {% for item in transactions %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.value }}</td>
                    <td>{{ item.rate }}%</td>
                    <td>{{ item.duty }}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="2">TOTAL</td>
                    <td>{{ total_value }}</td>
                    <td>-</td>
                    <td>{{ total_duty }}</td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Section C: Declaration</div>
        <p>I declare that the information provided in this report is true and correct.</p>
        <div class="info-item"><strong>Signature:</strong></div>
        <div class="signature-box">
            <!-- Placeholder for electronic signature -->
        </div>
        <div class="info-item"><strong>Date:</strong> {{ report_date }}</div>
    </div>

    <div class="footer">
        Generated by FinAgent Cross-Border Finance Tool on {{ report_date }}
    </div>
</body>
</html>
"""

# ==========================================
# 2. 核心逻辑
# ==========================================


def process_data(df: pd.DataFrame, tax_rate: float) -> pd.DataFrame:
    """
    处理CSV数据，计算税额
    """
    # 字段映射与填充
    df = df.copy()

    # 尝试映射中文列名到标准字段
    col_map = {
        "商品名称": "item_name",
        "数量": "quantity",
        "完税价格": "dutiable_value",
        "Item Name": "item_name",
        "Quantity": "quantity",
        "Dutiable Value": "dutiable_value",
    }

    # 重命名存在的列
    df.rename(
        columns={k: v for k, v in col_map.items() if k in df.columns}, inplace=True
    )

    # 确保必要列存在，缺失填充 "无" 或 0
    required_cols = {
        "item_name": "无 (Unknown Item)",
        "quantity": 0,
        "dutiable_value": 0.0,
    }

    for col, default in required_cols.items():
        if col not in df.columns:
            df[col] = default
        else:
            df[col] = df[col].fillna(default)

    # 计算逻辑
    # 确保数值类型
    df["dutiable_value"] = pd.to_numeric(df["dutiable_value"], errors="coerce").fillna(
        0.0
    )
    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce").fillna(0)

    df["tax_rate"] = tax_rate
    df["duty_amount"] = df["dutiable_value"] * (tax_rate / 100.0)

    return df


def generate_pdf(context: dict) -> bytes:
    """
    使用 Jinja2 渲染 HTML 并通过 WeasyPrint 转换为 PDF
    """
    template = Template(ATO_REPORT_TEMPLATE)
    html_content = template.render(context)

    # 生成 PDF
    pdf_file = io.BytesIO()
    HTML(string=html_content).write_pdf(pdf_file)
    pdf_file.seek(0)
    return pdf_file.getvalue()


# ==========================================
# 3. Streamlit UI
# ==========================================
def app():
    st.title("🧾 ATO跨境货物贸易税务报表生成器")

    # Sidebar: 配置
    with st.sidebar:
        st.header("1. 纳税人信息配置")
        abn = st.text_input("ABN (Australian Business Number)", value="12 345 678 901")
        company_name = st.text_input("公司名称", value="Example Trading Pty Ltd")
        contact = st.text_input("联系人", value="John Doe")

        st.header("2. 税率配置")
        tax_rate = st.slider("关税税率 (%)", 0.0, 20.0, 5.0, 0.5)

        st.markdown("---")
        st.markdown("### 模板下载")
        template_df = pd.DataFrame(
            {
                "商品名称": ["电子元件", "纺织品"],
                "数量": [1000, 500],
                "完税价格": [50000.00, 12000.50],
            }
        )
        st.download_button(
            "📥 下载CSV模板",
            template_df.to_csv(index=False).encode("utf-8"),
            "tax_template.csv",
            "text/csv",
        )

    # Main: 上传与生成
    st.subheader("3. 数据上传与处理")
    uploaded_file = st.file_uploader("上传交易流水CSV", type=["csv"])

    if uploaded_file:
        try:
            raw_df = pd.read_csv(uploaded_file)
            st.write("原始数据预览:", raw_df.head())

            # 处理数据
            processed_df = process_data(raw_df, tax_rate)

            st.subheader("4. 税额计算结果")
            st.dataframe(
                processed_df.style.format(
                    {
                        "dutiable_value": "${:,.2f}",
                        "duty_amount": "${:,.2f}",
                        "tax_rate": "{:.1f}%",
                    }
                )
            )

            # 汇总数据
            total_value = processed_df["dutiable_value"].sum()
            total_duty = processed_df["duty_amount"].sum()

            c1, c2 = st.columns(2)
            c1.metric("总完税价格 (Total Value)", f"${total_value:,.2f}")
            c2.metric("应纳关税总额 (Total Duty)", f"${total_duty:,.2f}")

            if st.button("生成ATO申报PDF"):
                # 准备渲染上下文
                transactions = []
                for _, row in processed_df.iterrows():
                    transactions.append(
                        {
                            "name": str(row["item_name"]),
                            "quantity": str(row["quantity"]),
                            "value": f"${row['dutiable_value']:,.2f}",
                            "rate": f"{row['tax_rate']:.1f}",
                            "duty": f"${row['duty_amount']:,.2f}",
                        }
                    )

                context = {
                    "abn": abn,
                    "company_name": company_name,
                    "contact": contact,
                    "report_date": datetime.now().strftime("%Y-%m-%d"),
                    "transactions": transactions,
                    "total_value": f"${total_value:,.2f}",
                    "total_duty": f"${total_duty:,.2f}",
                }

                with st.spinner("正在生成PDF报表..."):
                    try:
                        pdf_bytes = generate_pdf(context)
                        st.success("报表生成成功！")
                        st.download_button(
                            label="📄 下载ATO报表 (PDF)",
                            data=pdf_bytes,
                            file_name=f"ATO_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                            mime="application/pdf",
                        )
                    except Exception as e:
                        st.error(f"PDF生成失败: {str(e)}")
                        st.info(
                            "提示: WeasyPrint 可能需要系统级依赖 "
                            "(libcairo2, libpango-1.0-0 等)。"
                            "如果运行在受限环境，请联系管理员安装。"
                        )

        except Exception as e:
            st.error(f"文件处理错误: {str(e)}")


if __name__ == "__main__":
    st.set_page_config(page_title="ATO税务报表生成工具", page_icon="🧾")
    app()
